# Generated by Django 2.2.16 on 2022-10-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221009_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='recipes', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
